### ISSUE TITLE
Add Quotes

### ISSUE THREAD

**Issue by JayShukla8** [JayShukla8/Quotes#2]
- update the data.json file. (don't forget to add comma , before inserting new entry.)
- Limit it to 1 quote.
- I'll check the pr directly, no assigning.

**Comment by georgioupanayiotis** [comment]
@JayShukla8 can you assign me this ticket ?

**Comment by JayShukla8** [comment]
i mean, if you want to, then sure. Go ahead.

**Comment by georgioupanayiotis** [comment]
Yes i will add 10 more quotes...

**Comment by georgioupanayiotis** [comment]
check it out here https://github.com/JayShukla8/Quotes/pull/4 
@JayShukla8  @DebarjunChakraborty  merge it and add label `hacktoberfest-accepted`

**Comment by JollyJolli** [comment]
Hey there!
I would like to help adding more quotes!

**Comment by vigneshs-dev** [comment]
Hi... I also want to add some quotes for your webpage...Can you assign me this task ?

**Comment by shreyannandanwar** [comment]
Hey,
I also want to add more quotes!!
Can you assign me this task

**Comment by 1-SubhamSingh** [comment]
Hey there,
I'll like to append more quotes to your project ,  can you please assign me this task.

**Comment by Sai-Pratham05** [comment]
Hi Jay, can you assign me this task?

**Comment by MehediMubin** [comment]
Hello @JayShukla8,
I want to add a quote. Can you please assign me?
Thanks

**Comment by codebydeep** [comment]
Hi @JayShukla8  I would love to work on this issue. 
Can you assign it to me ?

**Comment by akku-07** [comment]
Id like to add a quote too!
can you assign this issue to me as well?

**Comment by pulkitgxrg** [comment]
I would also like to add some quotes too!
Can you assign me this issue as well?

**Comment by TheRaj71** [comment]
Issue: #2 Add 70+ New Quotes to Database
Description
I propose adding 70+ new quotes to the existing dataset. These quotes come from a diverse range of authors and cover topics such as motivation, life lessons, and creativity. This addition will enrich the content offering and provide users with fresh perspectives.

Use Case
Expanding the quote database will enhance user experience by offering a wider selection of content, encouraging more engagement with the platform.

Benefits
Increased Variety: More topics and authors covered.
User Engagement: Improved user interaction due to diverse, fresh content.
Scalability: Moves the project closer to its content milestones.
Suggested Solution
I can submit a pull request with the 70+ new quotes, ensuring proper formatting and uniqueness in the dataset.

kindly assign me this issue

**Comment by Harshh18** [comment]
Hey @JayShukla8 , I would love to contribute here, kindly assign me too.

**Comment by Sujal942** [comment]
I want to contribute in this can you assign me too.

**Comment by Samyak137** [comment]
I want to work on that will you please assign it to me.

**Comment by Pariyul** [comment]
Hello sir, can you assign this to me?

**Comment by codebydeep** [comment]
Can I add some new Quotes? @JayShukla8
