### ISSUE TITLE
Quote Rating System ⭐

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [JayShukla8/Quotes#24]
Allow users to rate or "like" quotes, and create a "Top Rated" section.

**Comment by JayShukla8** [comment]
ok, you can work on that. maybe just add a small 🤍 button in the quote container.

**Comment by TheRaj71** [comment]
**Issue: Add Star Rating System with Local Storage for Quotes**
Description
I propose adding a star rating system to the quotes project, where users can rate individual quotes and have their ratings saved in browser local storage. This ensures that users' ratings persist across sessions, allowing them to view their previously rated quotes each time they revisit the platform.

Use Case
This feature provides users with the ability to engage more meaningfully by rating their favorite quotes. Since ratings are stored in local storage, users will have a personalized experience, retaining their ratings even after closing and reopening the browser.

Benefits
Persistent User Interaction: Ratings saved in local storage ensure that users' preferences are remembered across sessions.
Enhanced Engagement: Allows users to interact with the content beyond reading, giving them a reason to return and check their previous ratings.
Personalized Experience: Each user gets a custom experience with their rating history stored locally.
Suggested Solution
I have implemented a star rating system that stores user ratings in local storage. The feature is fully functional and works across multiple sessions. A pull request can be submitted to integrate this feature.

here are some attaachments of feature implemetned
![Screenshot 2024-10-01 235219](https://github.com/user-attachments/assets/93cc048a-ca34-4985-ab12-6ec1ce5f8c94)

so kindly assign me this issue
